development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:22fca16b9a35db1794cae0e0583c687f@pike.redistogo.com:9875/
  channel_prefix: message_me_production
